### ISSUE TITLE
start 신호를 보낼 때 done 신호 처리

### ISSUE THREAD

**Issue by HIDDEN-IU** [ECE4278/lab2#2]
<문제>
DMA_CMD 레지스터의 start를 1로 만들면 DMA가 시작되고, 이때 done이 0이 되어 또다른 DMA를 시작하지 못하는 것으로 알고 있습니다.
그래서 DMA_CMD(start)에 1이 입력되면 자동으로 DMA_STATUS(done)에 0이 입력되도록 설계하였습니다.
하지만 이렇게 설계하니 done이 영원히 1로 돌아오지 않아 TB가 DMA가 끝나지 않았다고 판단하는 것 같습니다.
(done을 reset 이후 만지지 않으면 정상적으로 실행됩니다)

<질문>
현재는 DMA가 없으니 done이 그냥 1로 고정인건가요?
아니면 나중에 done을 바꿔주는 회로를 추가로 설계하게 되나요? 

후자의 경우 DMA_STATUS가 read only인 것으로 알고 있는데 DMA_CFG 모듈 밖에서 어떻게 done을 바꿀 수 있는지도 궁금합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

질문 1에 대한 답변 > 현재는 1로 고정한다고 생각해도 됩니다. done 신호를 만드는 모듈은 추후에 만듭니다.
질문 2에 대한 답변 > DMA_STATUS가 read only인 것은 "소프트웨어" 입장에서 말하는 겁니다. 소프트웨어 입장에서는 done 신호를 읽기만 합니다. done 신호를 만드는 것은 하드웨어(DMA_CFG가 아닌 다른 모듈)의 몫입니다. (DMA_CFG는 done 신호를 입력으로 받는 모듈로, done 신호를 생성하는 모듈은 아닙니다.)
