### ISSUE TITLE
wren 신호의 의미를 알 수 있을까요?

### ISSUE THREAD

**Issue by webserver3315** [ECE4278/lab2#4]
조교님 과제를 진행하다가 wren 의미가 궁금해서 질문드리게 되었습니다.
APB에서 명시된 signal 은 아닌 것 같은데, 코드 주석상으로는 penable 과 동일해보여서 의문이 들었습니다.
wren 신호의 의미를 알 수 있을까요?

그리고, tab 공백이랑 코드 indent(space 3개)가 안맞고, 자동indent 등이 안되어 번거로운데 혹시 User마다 각각 vimrc를 수정할 수 있는 권한이 있나요?
감사합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

먼저 늦게 답변드려서 죄송합니다. (앞으로 한 일주일정도는 문의사항들을 늦게 확인할것 같습니다. 양해 부탁드립니다.)

1. wren은 우선 penable과 다릅니다. wren은 DMA_CFG 내부에서 사용하는 신호이고, penable은 APB에서 사용하는 신호라는 점에서 우선 다릅니다. DMA_CFG 입장에서 wren은 외부로부터 받아오는 write data를 레지스터에 저장해야할 수 있을 때 1로 만들면 되는데,  wren이 1이 되려면 주석에서 명시한것처럼 penable 신호뿐만 아니라 psel신호와 pwrite 신호도 고려해야합니다. (이 부분이 이해가 안된다면 다시 질문해주세요.)

2. vimrc는 현재 user마다 수정할 수 있는 권한이 있으며 자유롭게 수정하셔도 됩니다. 만약에 권한 오류가 발생한다면 해당 아이디를 저에게 알려주시면 다시 한 번 체크해보도록 하겠습니다.

감사합니다.
