### ISSUE TITLE
lab2 과제 중 DMA_CMD에 관하여 질문이 있습니다.

### ISSUE THREAD

**Issue by Zoon17** [ECE4278/lab2#5]
안녕하십니까, 과제를 하던 중 DMA_CMD에 대해서 궁금증이 생겨 질문 드립니다.

제공해주신 Register Map을 보면 DMA_CMD 라는 register가 할당되어 있고
해당 register에 write까지 할 수 있게 되어 있습니다.

하지만 제공해주신 lab2 source code를 보면 DMA_CMD에 해당하는
'start' variable을 reg type으로 선언하지 않고 wire로 선언한 후에 
continuous assignment를 통해서 combinational block으로 구현하도록 되어 있습니다.

물론 위와 같은 방식으로 해도 결과는 크게 문제 없을텐데
저 wire type으로 선언된 'start'가 정확히 register 라고 보기 어렵지 않나 생각하고
값도 write하는게 아니라 combinational block이어서 

제공해주신 DMAC specification과 코드가 조금 차이점이 있다는 생각이 들었습니다.

제 배움이 부족해서 이러한 생각이 정확한 접근인지 궁금하고, 
혹시 이러한 방식으로 코드를 제공해주신 이유가 있다면 그 점이 궁금합니다.

++(DMA_STATUS도 별도 register 사용하지 않고 바로 input 값을 사용하는지 궁금합니다)

**Comment by dale40** [comment]
학생이 이해한 것이 맞습니다.

수업에서 SFR이라고 이야기를 했지만, 실제 모든 SFR들이 물리적인 register에 맵핑되는 것은 아닙니다.
이번 실습에서 command register는 실제 register에 저장되지 않고, combinational logic을 통해서 만들어지고 사라집니다. 비슷하게 status register도 별개의 register를 사용하지 않고, input값을 바로 사용하는 것을 의도했습니다.

실제 IP들을 설계하는 데에서도 비슷합니다. 일부 SFR들(특히 read/write가 가능한 SFR들)은 레지스터에 맵핑되어 값을 저장하지만, write-only SFR들은 register등에 저장할 필요가 없어 combinational logic으로 만들어져서 pulse를 만들고 끝나는 경우도 있고, read-only SFR들은 기존에 있는 combinational signal을 바로 연결해서 사용하기도 합니다.
